[[rule]]
name = "trailing-whitespace"
pattern = "\\s+\\n$"
enforce = true
comment = "Found trailing whitespace at line end"

[[rule]]
name = "not-centered-dots-within-operators"
pattern = "[=+(inter)(union)][\\s&]*dots[^\\.]"
enforce = true
comment = "Please use dots.c within operators"

[[rule]]
name = "centered-dots-within-commas"
pattern = "[,][\\s&]*dots\\.c"
enforce = true
comment = "Please use dots within ,"

[[rule]]
name = "formula-without-space-after-cjk-character"
pattern = "[^：，、。！？（）【】—；“”‘’…\\s\\x20-\\x7E]\\$"
enforce = true
comment = "Missing space between CJK character and $"

[[rule]]
name = "cjk-character-without-space-after-formula"
pattern = "\\$[^：，、。！？（）【】—；“”‘’…\\s\\x20-\\x7E]"
enforce = true
comment = "Missing space between $ and CJK character"

[[rule]]
name = "forbid-任一"
pattern = "任一"
enforce = true
comment = "Please use 任意 instead of 任一"

[[rule]]
name = "forbid-对于所有"
pattern = "对于所有"
enforce = true
comment = "Please use 对于任意 instead of 对于所有"

[[rule]]
name = "ambiguous-poly-notation"
pattern = "Poly_[a-z]\\("
enforce = true
comment = "Missing space after Poly_m"

[[rule]]
name = "use-tab-as-indent"
pattern = "^[ ]+"
enforce = true
comment = "Please use tab as indent instead of spaces"
