#let ee = "e"
#let ii = "i"
#let span = $op("span")$
#let null = $op("null")$
#let range = $op("range")$
#let Poly = math.cal("P")
#let LinearMap = math.cal("L")
#let complexification(vv) = $vv_upright(C)$
#let rhs = "R.H.S."
#let lhs = "L.H.S."
#let restricted(ff, uu) = $ff|_uu$
#let Permutation(nn) = $cal(P)_nn$
