name: Build and Deploy PDF

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python3
        uses: actions/setup-python@v5.4.0
      - name: Build PDF
        run: |
          pip install -r requirements.txt
          python3 make.py
      - name: Move PDF to public directory
        run: |
          mkdir -p public
          mv main.pdf public/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'public'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

